### ISSUE TITLE
[MOHIST 532] Protectionstones error

### ISSUE THREAD

**Issue by Scrulius** [Teneted/Tenet#1271]
Protectionstones isnt working on the last versions of mohist

Working perfect on 514

Plugin: https://www.spigotmc.org/resources/protectionstones-updated-for-1-13-1-16-wg7.61797/

Console error:

[23:26:47] [Server thread/ERROR] [Minecraft/]: Could not pass event PlayerJoinEvent to ProtectionStones v2.8.3
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[forge:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[forge:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:573) ~[forge:?]
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:257) ~[?:?]
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:169) ~[?:?]
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:72) ~[?:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:234) ~[?:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:141) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1054) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:331) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:944) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:759) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:270) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
	at dev.espi.protectionstones.ListenerClass.onPlayerJoin(ListenerClass.java:70) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[forge:?]
	... 15 more

**Comment by Scrulius** [comment]
bump

**Comment by Scrulius** [comment]
Hi? Bump.

**Comment by Scrulius** [comment]
Bump

**Comment by Shawiizz** [comment]
It's not needed to say bump. This will not make your issue fixed faster

**Comment by Shawiizz** [comment]
Please be patient ^_^

**Comment by Scrulius** [comment]
Sorry! thanks for responding man ^^

**Comment by KR33PYK1NG** [comment]
ProtectionStones is working in Mohist 551.

**Comment by Scrulius** [comment]
No, protectionStones isnt working in mohist 551/553

The plugin loads and it doesn't work at all

Try to create a region or get a stone, also not even the commands work

**Comment by KR33PYK1NG** [comment]
> 
> 
> No, protectionStones isnt working in mohist 551/553
> 
> The plugin loads and it doesn't work at all
> 
> Try to create a region or get a stone, also not even the commands work

IIRC I tested both region creation and command execution, and it worked.
Are you installing this plugin alongside WorldGuard+WorldEdit?

**Comment by Scrulius** [comment]
Im using:
Worldedit 7.2.5
Worldguard 7.0.4
ProtectionStones 2.8.3

And again, working perfect on 514 :(

If you fix it I will pay you 5€ on paypal ^-^ (it's not much but it's for thanking you)

**Comment by KR33PYK1NG** [comment]
> 
> 
> No, protectionStones isnt working in mohist 551/553
> 
> The plugin loads and it doesn't work at all
> 
> Try to create a region or get a stone, also not even the commands work

I tried once again and I still cannot reproduce your issue.
![n22](https://user-images.githubusercontent.com/75280223/117722262-84e49000-b1e9-11eb-8dce-5eb8cdf464ce.png)
My bet is that one of your plugins/mods is conflicting with ProtectionStones. You can remove them one by one to see if it's the case.

**Comment by Scrulius** [comment]
I have started it only with worldedit, worldguard and protectionstones

 I can be 100% sure that the problem is from mohist, since the plugin works perfectly on mohist 514 with all mods and plugins

New errors: https://pastebin.com/s8KweNuz

I get an error with fairylights, but if I delete it now I get another error but with druidcraft and if I delete druidcraft I get an error with quark ...

Mohist version 560

**Comment by KR33PYK1NG** [comment]
@Scrulius, is this the only error that occurs with the plugin?

**Comment by Scrulius** [comment]
that I know, yeah, it only happens with protectionstones

**Comment by KR33PYK1NG** [comment]
Fixed in c515aa1

**Comment by Scrulius** [comment]
Hi! the errors still here! Im using Mohist 563

Errors:
https://pastebin.com/TrfeJa61


And thank you very much for your effort, I hope you can fix it ^-^


Do you have patreon? I would be happy to help us

**Comment by KR33PYK1NG** [comment]
> And thank you very much for your effort, I hope you can fix it ^-^
> Do you have patreon? I would be happy to help us

You can support Mohist by using any of the links in "Sponsor this project" block in right sidebar [here](https://github.com/Mohist-Community/Mohist).

**Comment by KR33PYK1NG** [comment]
Regarding your issue - try again with build 566.

**Comment by Scrulius** [comment]
Now its working, thanks man, you are the best

I have joined your patreon, it is not a lot of money but I hope it can help you a little


Thanks for your help! ^^
