### ISSUE TITLE
Bad packet id 9

### ISSUE THREAD

**Issue by NovaPixell** [Teneted/Tenet#416]
When I try to update Mohist to the latest build. If I try to enter, in console I have this error:
guys urgent problem

  Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id 9

**Comment by TansuoTro** [comment]
Please use the latest build, this problem has been fixed

**Comment by NovaPixell** [comment]
I have used the #608 build, and the problem alredy exists

**Comment by qqqqww1** [comment]
Please try to delete your server.properties and restart server

**Comment by NovaPixell** [comment]
okay, now it works! the new server.properties is a little bit short than the old

**Comment by lushangkan** [comment]
This problem does not seem to be resolved.

**Comment by NovaPixell** [comment]
Now I'm on vacation, I don't know if they have fixed with other builds... Let's hope they do

**Comment by lushangkan** [comment]
> Now I'm on vacation, I don't know if they have fixed with other builds... Let's hope they do

Could you please tell us how this problem arises?

**Comment by Thrathra** [comment]
Hi, I can confirm that the bug is still present on recent server versions.

How to reproduce:

1) Create a new server using the latest Mohist jar.
2) Try to connect.
3) Bad packet 9

More info:
Server version: Mohist-1.12.2-65f6c8a-server.jar
Client forge version: 14.23.5.2854
Server mods / plugins: None

**Comment by NovaPixell** [comment]
> Hi, I can confirm that the bug is still present on recent server versions.
> 
> How to reproduce:
> 
> 1. Create a new server using the latest Mohist jar.
> 2. Try to connect.
> 3. Bad packet 9
> 
> More info:
> Server version: Mohist-1.12.2-65f6c8a-server.jar
> Client forge version: 14.23.5.2854
> Server mods / plugins: None

Thank you so much for saying how to reproduce it, even if it was very easy to do it. I hope they solve this problem soon, although I think the developers are on vacation.

**Comment by Shawiizz** [comment]
As i said on Discord, this error is caused by this commit https://github.com/Mohist-Community/Mohist/commit/1669f1f34836513919567793d1ea4c685d2c08df

**Comment by NovaPixell** [comment]
Will you soon release a build that fixes the problem?

**Comment by Shawiizz** [comment]
I don't know because i'm not a dev... But i hope this will be fixed as soon as possible

**Comment by NovaPixell** [comment]
Have you solved it? I see that build 631 has failed. I also see that there are references to paper 1.16 patches, what does it means?

**Comment by Shawiizz** [comment]
The issue is here on the build 632 (i didn't tested 633 yet)
Edit : This issue is also here on build 633

**Comment by NovaPixell** [comment]
Okay, and why did you close this issue?

**Comment by PierreBouffartigue** [comment]
This problem is solved, and so this issue has been closed as it is no longer useful

**Comment by Shawiizz** [comment]
It's not sloved for me

**Comment by Arth-Patel** [comment]
It is also not solved for me

**Comment by lushangkan** [comment]
[该](https://github.com/Mohist-Community/Mohist/commit/1669f1f34836513919567793d1ea4c685d2c08df)提交导致Bad Packet id 9问题。
[This](https://github.com/Mohist-Community/Mohist/commit/1669f1f34836513919567793d1ea4c685d2c08df) commit caused the Bad Packet id 9 issue.
