### ISSUE TITLE
[1.7.10] Crash with RecurrentComplex

### ISSUE THREAD

**Issue by GedeonGrays** [Teneted/Tenet#53]
_Hello o/_

**Mohist Version:** Build 61
**RecurrentComplex Version:** 0.9.7.1.1
**Crash report:** https://pastebin.com/hS9WmtnL

Crash during server startup.

**Comment by Mgazul** [comment]
Fixed

**Comment by GedeonGrays** [comment]
> Fixed

Unfortunately RecurrentComplex is still not working.

**Mohist Version:** Build 66
**Crash report:** crash report has not changed
